configfile: "config/config.yml"
include: "parameters.smk"

# --- convert scRNA seurat .rds to h5 ---
# include: "rules/0-seurat_to_h5.smk"

# --- coexpression xenium contamination metric (unused) ---
# include: "rules/0-coexpression.smk"
# include: "rules/0-coexpression_cross_panel.smk"
# include: "rules/1-coexpression_plot.smk"
# include: "rules/1-coexpression_scrnaseq_references.smk"

# --- xenium sklearn silhouette scores (unused) ---
# include: "rules/0-silhouette.smk"
# include: "rules/1-silhouette_plot.smk"

# --- xenium scib metrics ---
# include: "rules/0-scib_metrics.smk"
# include: "rules/0-scib_metrics_singlets.smk"
# include: "rules/1-scib_metrics_corrected_counts.smk"
# include: "rules/2-scib_metrics_plot.smk"

# --- xenium TLS detection (unused) ---
# include: "rules/0-detect_tls.smk"

# --- xenium and scRNA UMAPS ---
# include: "rules/0-embedding.smk"
# include: "rules/1-embedding_plot.smk"

# include: "rules/0-embedding_singlets.smk"
# include: "rules/1-embedding_singlets_plot.smk"

# include: "rules/0-embedding_sample.smk"
# include: "rules/1-embedding_sample_plot.smk"

# include: "rules/1-embedding_scrnaseq.smk"
# include: "rules/2-embedding_scrnaseq_plot.smk"
# include: "rules/1-embedding_scrnaseq_joint.smk"
# include: "rules/2-embedding_scrnaseq_joint_plot.smk"

# include: "rules/0-embedding_restricted_genes_and_samples.smk"
# include: "rules/0-embedding_restricted_genes.smk"
# include: "rules/1-embedding_restricted_genes_scrnaseq.smk"
# include: "rules/1-embedding_restricted_genes_and_samples_scrnaseq.smk"
# include: "rules/1-embedding_restricted_genes_plot.smk"
# include: "rules/2-embedding_restricted_genes_scrnaseq_plot.smk"
# include: "rules/1-embedding_restricted_genes_and_samples_plot.smk"
# include: "rules/2-embedding_restricted_genes_and_samples_scrnaseq_plot.smk"

# --- xenium run ovrlpy and resolvi ---
# include: "rules/0-ovrlpy.smk"
# include: "rules/0-resolvi.smk"
# include: "rules/0-resolvi_supervised.smk"
# include: "rules/0-resolvi_panel.smk"
# include: "rules/0-resolvi_panel_supervised.smk"

# --- xenium run coexpression with corrected counts (unused) ---
# include: "rules/1-coexpression_corrected_counts.smk"
# include: "rules/1-coexpression_corrected_counts_plot.smk"
# include: "rules/2-embedding_corrected_counts.smk"
# include: "rules/3-embedding_corrected_counts_plot.smk"

# --- xenium contamination metrics ---
# include: "rules/2-contamination_metrics_diffexpr.smk"
# include: "rules/2-contamination_metrics_logreg.smk"
# include: "rules/2-contamination_metrics_diffexpr_corrected_counts.smk"
# include: "rules/2-contamination_metrics_logreg_corrected_counts.smk"

# include: "rules/3-contamination_metrics_diffexpr_specificity_boxplot.smk"
# include: "rules/3-contamination_metrics_diffexpr_specificity_logreg_boxplot.smk"
# include: "rules/3-contamination_metrics_diffexpr_sensitivity_boxplot.smk"
# include: "rules/3-contamination_metrics_cosine_similarity_scrnaseq.smk"

rule all:
    input:
        # rules.seurat_to_h5_all.input,
        #
        # rules.coexpression_all.input,
        # rules.coexpression_cross_panel_all.input,
        # rules.coexpression_scrnaseq_references_all.input,
        # rules.coexpression_corrected_counts_all.input,
        # rules.coexpression_plot_panel_all.input,
        # rules.coexpression_plot_conditions_all.input,
        # rules.coexpression_corrected_counts_plot_panel_all.input,
        # rules.coexpression_corrected_counts_plot_conditions_all.input,
        #
        # rules.silhouette_all.input,
        # rules.silhouette_plot_panel_all.input,
        # rules.silhouette_plot_condition_all.input,
        #
        # rules.detect_tls_all.input,
        #
        # rules.embed_panel_all.input,
        # rules.embed_panel_plot_all.input,
        # rules.embed_condition_all.input,
        # rules.embed_condition_plot_all.input,
        #
        # rules.embed_panel_singlets_all.input,
        # rules.embed_panel_singlets_plot_all.input,
        # 
        # rules.embed_panel_scrnaseq_all.input,
        # rules.embed_panel_scrnaseq_plot_all.input,
        #
        # rules.embed_panel_scrnaseq_joint.input,
        # rules.embed_panel_scrnaseq_joint_plot_all.input,
        #
        # rules.embed_panel_restricted_genes_all.input,
        # rules.embed_panel_restricted_genes_scrnaseq_all.input,
        # rules.embed_panel_restricted_genes_and_samples_all.input,
        # rules.embed_panel_restricted_genes_and_samples_scrnaseq_all.input,
        #
        # rules.embed_panel_restricted_genes_plot_all.input,
        # rules.embed_panel_restricted_genes_and_samples_plot_all.input,
        # rules.embed_panel_restricted_genes_scrnaseq_plot_all.input,
        # rules.embed_panel_restricted_genes_and_samples_scrnaseq_plot_all.input,
        #
        # rules.embed_sample_all.input,
        # rules.embed_sample_plot_all.input,
        #
        # rules.embed_panel_corrected_counts_all.input,
        # rules.embed_panel_corrected_counts_plot_all.input,
        # rules.embed_condition_corrected_counts_all.input,
        # rules.embed_condition_corrected_counts_plot_all.input,
        #
        # rules.resolvi_training_all.input,
        # rules.resolvi_training_supervised_all.input,
        # rules.resolvi_inference_all.input,
        # rules.resolvi_inference_supervised_all.input,
        #
        # rules.resolvi_panel_training_all.input,
        # rules.resolvi_panel_training_supervised_all.input,
        # rules.resolvi_panel_inference_all.input,
        # rules.resolvi_panel_inference_supervised_all.input,
        # #
        # rules.ovrlpy_all.input,
        # rules.ovrlpy_correction_all.input,
        #
        # rules.scib_metrics_panel_all.input,
        # rules.scib_metrics_panel_singlets_all.input,
        # rules.scib_metrics_panel_corrected_counts_all.input,
        # rules.scib_metrics_panel_plot_all.input,
        #
        # rules.contamination_metrics_diffexpr_all.input,
        # rules.contamination_metrics_logreg_all.input,
        # rules.contamination_metrics_diffexpr_corrected_counts_all.input,
        # rules.contamination_metrics_logreg_corrected_counts_all.input,
        #
        # rules.contamination_metrics_specificity_boxplot_all.input,
        # rules.contamination_metrics_specificity_logreg_boxplot_all.input,
        # rules.contamination_metrics_sensitivity_boxplot_all.input,
        # rules.contamination_metrics_cosine_similarity_scrnaseq_boxplot_all.input,

